apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- db-backup-cj.yaml

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: 30e75a33f6a0cd615f878d83ff559e17533b58b9
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: 30e75a33f6a0cd615f878d83ff559e17533b58b9
