apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ./../../base

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: 46346ab22fbd7a5a3a3d5a93c2c8188d83b907c2
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: 46346ab22fbd7a5a3a3d5a93c2c8188d83b907c2
