apiVersion: v1
kind: Service
metadata:
  name: ping-pong-postgres-svc
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: ping-pong-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-pong-postgres-sts
spec:
  serviceName: ping-pong-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-postgres
  template:
    metadata:
      labels:
        app: ping-pong-postgres
    spec:
      containers:
        - name: ping-pong-postgres
          image: postgres:17
          env:
          - name: POSTGRES_PASSWORD
            value: "postgres"
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: ping-pong-postgres-vol
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: ping-pong-postgres-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
