apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
