apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/backend-dep.yaml
- manifests/backend-svc.yaml
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres-secret.yaml
- manifests/postgres-sts.yaml
- manifests/service.yaml
- manifests/todo-backend-wikipedia-cj.yaml
