apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: 5fc10b49dcfa02adbdf566cb190647ad8fa855db
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: 5fc10b49dcfa02adbdf566cb190647ad8fa855db

resources:
- manifests/backend-dep.yaml
- manifests/backend-svc.yaml
- manifests/db-backup-cj.yaml
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres-secret.yaml
- manifests/postgres-sts.yaml
- manifests/service.yaml
- manifests/todo-backend-wikipedia-cj.yaml
