apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: LOGHTTPIMG
  newName: vsirvio/http-endpoint-app
  newTag: dd99d7ec9d5edebe87708698a3042974cdc96132
- name: LOGWRITERIMG
  newName: vsirvio/log-writer-app
  newTag: dd99d7ec9d5edebe87708698a3042974cdc96132

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/service.yaml
