apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: LOGHTTPIMG
  newName: vsirvio/http-endpoint-app
  newTag: 5fc10b49dcfa02adbdf566cb190647ad8fa855db
- name: LOGWRITERIMG
  newName: vsirvio/log-writer-app
  newTag: 5fc10b49dcfa02adbdf566cb190647ad8fa855db

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/service.yaml
