apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: LOGHTTPIMG
  newName: vsirvio/http-endpoint-app
  newTag: 5acea28e17c2f9a7d0ff032b59a3d0b1b3c88376
- name: LOGWRITERIMG
  newName: vsirvio/log-writer-app
  newTag: 5acea28e17c2f9a7d0ff032b59a3d0b1b3c88376

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/service.yaml
