apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: LOGHTTPIMG
  newName: vsirvio/http-endpoint-app
  newTag: 7671278a9514393ac1c5b80dfc4c0e8e36f99e06
- name: LOGWRITERIMG
  newName: vsirvio/log-writer-app
  newTag: 7671278a9514393ac1c5b80dfc4c0e8e36f99e06

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/service.yaml
