apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: LOGHTTPIMG
  newName: vsirvio/http-endpoint-app
  newTag: 2632d16c6aa4671c806cce83a7eb14f47320fa61
- name: LOGWRITERIMG
  newName: vsirvio/log-writer-app
  newTag: 2632d16c6aa4671c806cce83a7eb14f47320fa61

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/service.yaml
