apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: LOGHTTPIMG
  newName: vsirvio/http-endpoint-app
  newTag: c741ddf0e74fdb9654e0984ff8b44f2985f96f57
- name: LOGWRITERIMG
  newName: vsirvio/log-writer-app
  newTag: c741ddf0e74fdb9654e0984ff8b44f2985f96f57

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/gateway.yaml
- manifests/route.yaml
- manifests/service.yaml
