name: Commit kustomization

on:
  push:
    paths: ['log_output/**', 'the_project/**', '.github/workflows/**']

jobs:
  commit-kustomization:
    name: Commit kustomization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images for log_output
        run: |-
          kustomize edit set image LOGHTTPIMG=vsirvio/http-endpoint-app:$GITHUB_SHA
          kustomize edit set image LOGWRITERIMG=vsirvio/log-writer-app:$GITHUB_SHA
        working-directory: './log_output'

      - name: Use right images for the_project
        run: |-
          kustomize edit set image PROJECT/IMAGE/BACKEND=vsirvio/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE/FRONTEND=vsirvio/todo-app:$GITHUB_SHA
        working-directory: './the_project'

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'log_output/kustomization.yaml the_project/kustomization.yaml'
          message: New version released ${{ github.sha }}
