name: Deploy the_project to production

on:
  push:
    tags: ['**']
    paths: ['the_project/**']

jobs:
  the-project-build-prod:
    name: Build the_project production release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish todo-backend
        run: |-
          docker build --tag "vsirvio/todo-backend:$GITHUB_SHA" .
          docker push "vsirvio/todo-backend:$GITHUB_SHA"
        working-directory: './the_project/todo-backend'

      - name: Build and publish todo-app
        run: |-
          docker build --tag "vsirvio/todo-app:$GITHUB_SHA" .
          docker push "vsirvio/todo-app:$GITHUB_SHA"
        working-directory: './the_project/todo-app'

  the-project-deploy-prod:
    name: Deploy the_project to production
    runs-on: ubuntu-latest
    needs: the-project-build-prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'VSirvio/dwk-project-config'
          token: ${{ secrets.CONFIG_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        run: |-
          kustomize edit set image PROJECT/IMAGE/BACKEND=vsirvio/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE/FRONTEND=vsirvio/todo-app:$GITHUB_SHA
        working-directory: './overlays/production'

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'overlays/production/kustomization.yaml'
          message: New production version released ${{ github.sha }}
