name: Build and publish the_project

on:
  push:
    paths: ['the_project/**', '.github/workflows/**']

jobs:
  build-publish-the-project:
    name: Build, Push, Release the_project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish todo-backend
        run: |-
          docker build --tag "vsirvio/todo-backend:$GITHUB_SHA" .
          docker push "vsirvio/todo-backend:$GITHUB_SHA"
        working-directory: './the_project/todo-backend'

      - name: Build and publish todo-app
        run: |-
          docker build --tag "vsirvio/todo-app:$GITHUB_SHA" .
          docker push "vsirvio/todo-app:$GITHUB_SHA"
        working-directory: './the_project/todo-app'
