name: Build and publish the_project

on:
  push:
    paths: ['the_project/**', '.github/workflows/**']

jobs:
  build-publish:
    name: Build, Push, Release the_project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish todo-backend
        run: |-
          docker build --tag "vsirvio/todo-backend:$GITHUB_SHA" .
          docker push "vsirvio/todo-backend$GITHUB_SHA"
        working-directory: './the_project/todo-backend'

      - name: Build and publish todo-app
        run: |-
          docker build --tag "vsirvio/todo-app:$GITHUB_SHA" .
          docker push "vsirvio/todo-app:$GITHUB_SHA"
        working-directory: './the_project/todo-app'

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        run: |-
          kustomize edit set image PROJECT/IMAGE/BACKEND=vsirvio/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE/FRONTEND=vsirvio/todo-app:$GITHUB_SHA
        working-directory: './the_project'

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'the_project/kustomization.yaml'
          message: New todo-app version released ${{ github.sha }}
